// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppCalendar = { id: CollectionId, summary: string, color?: Color, isPrimary?: boolean, 
/**
 * Google's `accessRole` (`owner`, `writer`, `reader`, `freeBusyReader`).
 * `reader` and `freeBusyReader` calendars reject every write.
 */
accessRole?: string, };
