// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEventType } from "./AppEventType.generated";

export type AppEvent = { id: string, remoteId?: string, remoteCollectionId?: string, taskId?: string, title: string, description?: string, startTime: string, endTime: string, type: AppEventType, rrule?: string, exdates?: Array<string>, recurringEventId?: string, originalStartTime?: string, cancelled?: boolean, updatedAt?: bigint, color?: string, _deleted?: boolean, etag?: string, dirty?: boolean, };
