// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEventFilterColumn } from "./AppEventFilterColumn.generated";
import type { FilterType } from "./FilterType.generated";

export type AppEventColumnDef = { id: AppEventFilterColumn, label: string, db_col: string, filter_type: FilterType, sortable: boolean, };
