// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEventFilterColumn } from "./AppEventFilterColumn.generated";
import type { SortDirection } from "./SortDirection.generated";

export type AppEventSort = { column: AppEventFilterColumn | null, direction: SortDirection | null, };
