// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEventFilterColumn } from "./AppEventFilterColumn.generated";

export type AppEventFilter = { column: AppEventFilterColumn | null, operator: string | null, value: unknown, };
