// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventFilterColumn } from "./EventFilterColumn.generated";

export type AppEventFilter = { column: EventFilterColumn | null, operator: string | null, value: unknown, };
