// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventStatus } from "./EventStatus.generated";

export type AppEvent = { id: string, remoteId?: string, remoteCollectionId?: string, taskId?: string, title: string, description?: string, startTime: string, endTime: string, rrule?: string, exdates?: Array<string>, recurringEventId?: string, originalStartTime?: string, status?: EventStatus, updatedAt?: string, color?: string, bgColor?: string, etag?: string, dirty?: boolean, isAllDay?: boolean, };
