// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppEvent = { id: string, remoteId?: string, remoteCollectionId?: string, taskId?: string, title: string, description?: string, startTime: string, endTime: string, rrule?: string, exdates?: Array<string>, recurringEventId?: string, originalStartTime?: string, cancelled?: boolean, updatedAt?: number, color?: string, _deleted?: boolean, etag?: string, dirty?: boolean, };
