// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterColumn } from "./FilterColumn";

export type AppFilter = { column: FilterColumn | null, operator: string | null, value: unknown, };
