// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTaskStatus } from "./AppTaskStatus";
import type { Subtask } from "./Subtask";

export interface AppTask { id: string, title: string, status?: AppTaskStatus, priority?: number, tags?: string[], subtasks?: Subtask[], parentTask?: string, dependencies?: string[], est?: number, added?: string, canvasX?: number, canvasY?: number, onCanvas?: boolean, remoteId?: string, notes?: string, tabs?: string, due?: string, _deleted?: boolean, updatedAt?: bigint, etag?: string, }
