// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTaskFilterColumn } from "./AppTaskFilterColumn.generated";

export type AppTaskFilter = { column: AppTaskFilterColumn | null, operator: string | null, value: unknown, };
