// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTaskFilterColumn } from "./AppTaskFilterColumn.generated";
import type { FilterType } from "./FilterType.generated";

export type AppTaskColumnDef = { id: AppTaskFilterColumn, label: string, db_col: string, filter_type: FilterType, sortable: boolean, };
