// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTaskFilterColumn } from "./AppTaskFilterColumn.generated";
import type { SortDirection } from "./SortDirection.generated";

export type AppTaskSort = { column: AppTaskFilterColumn | null, direction: SortDirection | null, };
