// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTaskStatus } from "./AppTaskStatus.generated";
import type { Subtask } from "./Subtask.generated";
import type { Tag } from "./Tag.generated";
import type { TaskPriority } from "./TaskPriority.generated";

export type AppTask = { id: string, title: string, status?: AppTaskStatus, priority?: TaskPriority, tags?: Array<Tag>, subtasks?: Array<Subtask>, parentTask?: string, dependencies?: Array<string>, est?: number, added?: string, canvasX?: number, canvasY?: number, onCanvas?: boolean, remoteId?: string, notes?: string, tabs?: string, due?: string, _deleted?: boolean, updatedAt?: bigint, etag?: string, dirty?: boolean, };
