// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskFilterColumn } from "./TaskFilterColumn.generated";

export type AppTaskFilter = { column: TaskFilterColumn | null, operator: string | null, value: unknown, };
