// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTaskStatus } from "./AppTaskStatus";
import type { TaskPriority } from "./TaskPriority";

export type AppTaskDefaults = { status: AppTaskStatus | null, priority: TaskPriority | null, tags: Array<string> | null, };
