// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventStatus } from "./EventStatus.generated";
import type { EventTiming } from "./EventTiming.generated";

/**
 * A single render-ready occurrence produced by the projection boundary.
 */
export type EventInstance = { 
/**
 * Row id for this occurrence: the master for rule-expanded instances, or
 * the override row for a moved instance. Edits target this id.
 */
id: EventId, 
/**
 * Stable identity for one occurrence, e.g. `master@2026-09-07`.
 */
occurrenceKey: string, title: string, description?: string, timing: EventTiming, 
/**
 * True when this instance came from a recurrence rule.
 */
recurring: boolean, rrule?: string, calendarId?: CollectionId, color?: Color, status: EventStatus, taskId?: TaskId, };
