// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The one place that decides whether a mirrored event is all-day or timed.
 *
 * Nothing outside this module may interpret `AppEvent::start_time` /
 * `end_time`; those remain wire-format strings for the push path only.
 */
export type EventTiming = { "kind": "allDay", startDate: string, endDateExclusive: string, } | { "kind": "timed", start: string, end: string, timezone: string | null, };
