// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppEvent } from "./AppEvent.generated";

export type LaidEvent = { event: AppEvent, startMins: number, endMins: number, lane: number, lanes: number, };
