// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigilProperties } from "./SigilProperties.generated";

export type ParsedSigils = { cleanTitle: string, properties: SigilProperties, };
