// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaidEvent } from "./LaidEvent.generated";

export type PlanDayLayout = { date: string, events: Array<LaidEvent>, };
