// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StopwatchState = { elapsed: number, runningSince: number | null, isBreak: boolean, breakAllowedMs: number, breakStartedAt: number | null, breakSoundPlayed: boolean, };
