// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncState = { is_syncing: boolean, error: string | null, next_sync_at: string | null, };
