//! Setting presentation metadata and the settings-screen schema.
//!
//! [`SettingMeta`] is generated from the `#[setting(..)]` attributes on
//! `AppSettings` by `#[derive(SettingsMeta)]`; this module only assembles the
//! generated metadata into tabs/sections for `get_settings_schema`.

use serde::Serialize;
use serde_json::Value;

use super::AppSettings;

/// One setting's presentation metadata, generated by `#[derive(SettingsMeta)]`.
///
/// Serialized into the `get_settings_schema` payload. `section` is not serialized:
/// it only routes the setting into the right tab/section during assembly.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SettingMeta {
    pub id: String,
    pub label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub keywords: Vec<String>,
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<SettingOption>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_value: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub danger: Option<bool>,
    #[serde(skip)]
    pub section: &'static str,
}

/// A select option; `value` is JSON so it can be a string or a number.
#[derive(Debug, Clone, Serialize)]
pub struct SettingOption {
    pub value: Value,
    pub label: String,
}

/// A tab/section in the settings screen. `key` is what `#[setting(section = ..)]`
/// references; tabs are grouped in first-appearance order.
struct SectionDef {
    key: &'static str,
    tab: &'static str,
    tab_label: &'static str,
    name: &'static str,
}

const SETTING_SECTIONS: &[SectionDef] = &[
    SectionDef {
        key: "plan_calendar",
        tab: "plan_screen",
        tab_label: "Plan screen",
        name: "Calendar",
    },
    SectionDef {
        key: "do_stopwatch",
        tab: "do_screen",
        tab_label: "Do screen",
        name: "Stopwatch",
    },
    SectionDef {
        key: "sync_integrations",
        tab: "sync",
        tab_label: "Sync and Backup",
        name: "Sync & Integrations",
    },
    SectionDef {
        key: "sync_danger",
        tab: "sync",
        tab_label: "Sync and Backup",
        name: "Danger Zone",
    },
    SectionDef {
        key: "keybindings",
        tab: "keybindings",
        tab_label: "Keybindings",
        name: "Keybindings",
    },
    SectionDef {
        key: "tracker_appearance",
        tab: "tracker_window",
        tab_label: "Tracker window",
        name: "Appearance",
    },
];

/// Button-only settings that act on the app rather than storing a value.
struct CustomSettingDef {
    section: &'static str,
    id: &'static str,
    label: &'static str,
    description: &'static str,
    keywords: &'static [&'static str],
    danger: bool,
}

const CUSTOM_SETTINGS: &[CustomSettingDef] = &[
    CustomSettingDef {
        section: "sync_integrations",
        id: "logout",
        label: "Sign out",
        description: "Sign out of your Google account.",
        keywords: &["logout", "signout", "google", "account"],
        danger: false,
    },
    CustomSettingDef {
        section: "sync_danger",
        id: "clear_all_data",
        label: "Clear All Data",
        description: "Permanently delete all your tasks, settings, logs, and other data from both this device and the cloud. This cannot be undone.",
        keywords: &["delete", "clear", "wipe", "reset", "factory", "all"],
        danger: true,
    },
];

#[derive(Serialize)]
struct SchemaSection {
    name: &'static str,
    settings: Vec<SettingMeta>,
}

#[derive(Serialize)]
struct SchemaTab {
    id: &'static str,
    label: &'static str,
    sections: Vec<SchemaSection>,
}

#[derive(Serialize)]
struct SchemaRoot {
    tabs: Vec<SchemaTab>,
}

fn custom_setting_meta(def: &CustomSettingDef) -> SettingMeta {
    SettingMeta {
        id: def.id.to_string(),
        label: def.label.to_string(),
        description: Some(def.description.to_string()),
        keywords: def
            .keywords
            .iter()
            .map(|word| (*word).to_string())
            .collect(),
        kind: "custom".to_string(),
        options: None,
        min: None,
        max: None,
        default_value: None,
        danger: def.danger.then_some(true),
        section: def.section,
    }
}

fn build_settings_schema() -> SchemaRoot {
    let mut tabs: Vec<SchemaTab> = Vec::new();
    let metadata = AppSettings::setting_metadata();

    for def in SETTING_SECTIONS {
        let mut settings: Vec<SettingMeta> = metadata
            .iter()
            .filter(|meta| meta.section == def.key)
            .cloned()
            .collect();
        settings.extend(
            CUSTOM_SETTINGS
                .iter()
                .filter(|custom| custom.section == def.key)
                .map(custom_setting_meta),
        );

        let section = SchemaSection {
            name: def.name,
            settings,
        };

        if let Some(tab) = tabs.iter_mut().find(|tab| tab.id == def.tab) {
            tab.sections.push(section);
        } else {
            tabs.push(SchemaTab {
                id: def.tab,
                label: def.tab_label,
                sections: vec![section],
            });
        }
    }

    SchemaRoot { tabs }
}

/// Serialize the schema to JSON.
///
/// Field order in the output relies on `serde_json`'s default `BTreeMap`
/// ordering (`preserve_order` off), so a checked-in golden byte diff would be
/// brittle; compare structurally instead.
pub(super) fn settings_schema_value() -> Value {
    // `SchemaRoot` is plain data, so serialization is infallible.
    serde_json::to_value(build_settings_schema()).unwrap_or(Value::Null)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;
    use std::collections::BTreeSet;

    /// The control kinds `SettingRow` knows how to render. `custom` is for the
    /// button-only pseudo-settings; anything else produces no control.
    const KNOWN_SETTING_KINDS: &[&str] = &[
        "select",
        "checkbox",
        "number",
        "time",
        "keybinding",
        "custom",
    ];

    fn schema_setting_ids() -> Vec<String> {
        let schema = settings_schema_value();
        let mut ids = Vec::new();

        for tab in schema["tabs"].as_array().expect("tabs") {
            for section in tab["sections"].as_array().expect("sections") {
                for setting in section["settings"].as_array().expect("settings") {
                    ids.push(setting["id"].as_str().expect("id").to_string());
                }
            }
        }

        ids
    }

    #[test]
    fn setting_metadata_covers_every_appsettings_field_exactly_once() {
        let metadata = AppSettings::setting_metadata();
        let ids: Vec<String> = metadata.iter().map(|meta| meta.id.clone()).collect();
        let unique: BTreeSet<String> = ids.iter().cloned().collect();
        assert_eq!(unique.len(), ids.len(), "duplicate metadata id");

        let defaults = serde_json::to_value(AppSettings::default()).expect("defaults");
        let expected: BTreeSet<String> = defaults
            .as_object()
            .expect("defaults object")
            .keys()
            .cloned()
            .collect();

        assert_eq!(unique, expected);

        for meta in &metadata {
            assert_eq!(
                meta.default_value.as_ref(),
                defaults.get(&meta.id),
                "{}",
                meta.id
            );
        }
    }

    #[test]
    fn schema_places_every_setting_exactly_once() {
        let ids = schema_setting_ids();
        let unique: BTreeSet<String> = ids.iter().cloned().collect();
        assert_eq!(unique.len(), ids.len(), "duplicate setting id in schema");

        let mut expected: BTreeSet<String> = AppSettings::setting_metadata()
            .iter()
            .map(|meta| meta.id.clone())
            .collect();
        expected.insert("logout".to_string());
        expected.insert("clear_all_data".to_string());

        assert_eq!(unique, expected);
    }

    #[test]
    fn every_setting_kind_is_known() {
        let kinds: Vec<String> = AppSettings::setting_metadata()
            .into_iter()
            .map(|meta| meta.kind)
            .chain(CUSTOM_SETTINGS.iter().map(|_| "custom".to_string()))
            .collect();

        for kind in kinds {
            assert!(
                KNOWN_SETTING_KINDS.contains(&kind.as_str()),
                "unknown setting kind '{kind}'; expected one of {KNOWN_SETTING_KINDS:?}"
            );
        }
    }

    #[test]
    fn every_setting_section_is_registered() {
        let registered: BTreeSet<&str> =
            SETTING_SECTIONS.iter().map(|section| section.key).collect();

        for meta in AppSettings::setting_metadata() {
            assert!(
                registered.contains(meta.section),
                "setting '{}' references unknown section '{}'; add it to SETTING_SECTIONS",
                meta.id,
                meta.section
            );
        }
        for custom in CUSTOM_SETTINGS {
            assert!(
                registered.contains(custom.section),
                "custom setting '{}' references unknown section '{}'; add it to SETTING_SECTIONS",
                custom.id,
                custom.section
            );
        }
    }

    #[test]
    fn numeric_select_options_keep_numeric_values() {
        let metadata = AppSettings::setting_metadata();
        let duration = metadata
            .iter()
            .find(|meta| meta.id == "default_task_duration")
            .expect("default_task_duration metadata");
        let options = duration.options.as_ref().expect("options");

        assert_eq!(
            options.first().map(|option| &option.value),
            Some(&serde_json::json!(0))
        );
        assert_eq!(
            options.get(1).map(|option| &option.value),
            Some(&serde_json::json!(15))
        );
    }
}
