//! App settings and per-component UI state storage.
//!
//! Two channels back persisted state:
//! - Typed, user-facing app settings are `AppSettings` fields stored as JSON rows
//!   in the `settings` table and read/written with [`get_settings`] / [`update_setting`].
//! - Arbitrary per-component UI state (filters, sorts, view modes, pane sizes)
//!   lives in the dedicated `ui_state` table via [`get_ui_state`] / [`set_ui_state`].
//!
//! The rule: if it is a typed app setting, it belongs in `AppSettings`; anything
//! else the frontend wants to remember goes to `ui_state`. Never smuggle UI state
//! into `settings` as ad-hoc `ui.*` keys. (The `settings` table also carries the
//! `google_*` OAuth rows written by `auth.rs`; those are not settings and are not
//! part of `AppSettings`.)
//!
//! Settings presentation metadata lives in `#[setting(..)]` attributes next to the
//! field it describes; [`get_settings_schema`] assembles the UI schema from them
//! and [`AppSettings::setting_metadata`] is generated by `#[derive(SettingsMeta)]`.
//!
//! This module is split into [`storage`] (the pool-level command bodies, value
//! decode/encode and the merge rule) and [`metadata`] (schema assembly); the
//! command functions stay here and only resolve the pool.
#![allow(clippy::struct_excessive_bools)]

mod metadata;
mod storage;

#[cfg(test)]
mod tests;

use crate::error::AppError;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use taskroot_macros::SettingsMeta;
use ts_rs::TS;

pub use metadata::{SettingMeta, SettingOption};

#[derive(Debug, Clone, Serialize, Deserialize, TS, SettingsMeta)]
#[ts(export, export_to = "../../src/lib/bindings/AppSettings.generated.ts")]
#[serde(default)]
pub struct AppSettings {
    #[setting(
        label = "Default View",
        keywords = ["calendar", "view", "month", "week"],
        kind = "select",
        section = "plan_calendar",
        options = [("month", "Month"), ("week", "Week")]
    )]
    pub default_calendar_view: String,
    #[setting(
        label = "Timeline View Start Time",
        keywords = ["timeline", "day", "start", "time", "scroll", "view"],
        kind = "time",
        section = "plan_calendar"
    )]
    pub day_timeline_start_view: i32,
    #[setting(
        label = "Default Duration",
        keywords = ["task", "duration", "estimate", "time"],
        kind = "select",
        section = "plan_calendar",
        options = [(0, "Not set"), (15, "15m"), (30, "30m"), (45, "45m")]
    )]
    pub default_task_duration: i32,
    #[setting(
        label = "Clock Style",
        keywords = ["stopwatch", "timer", "guzey", "counter", "flowtime"],
        kind = "select",
        section = "do_stopwatch",
        options = [
            ("counter", "Counter"),
            ("flowtime", "Flowtime"),
            ("guzey", "Guzey")
        ]
    )]
    pub clock_style: String,
    #[setting(
        label = "Allow stopwatch use without selecting task",
        keywords = ["stopwatch", "task", "requirement", "allow"],
        kind = "checkbox",
        section = "do_stopwatch"
    )]
    pub allow_stopwatch_without_task: bool,
    #[setting(
        label = "Flowtime Break Divisor",
        description = "How much break time you earn (e.g. 5 means 1 min break for every 5 mins of work).",
        keywords = ["flowtime", "break", "divisor", "rest"],
        kind = "number",
        section = "do_stopwatch",
        min = 1
    )]
    pub flowtime_break_divisor: i32,
    #[setting(
        label = "Enable Bidirectional Google Calendar Sync",
        description = "Self explanatory.",
        keywords = ["google", "calendar", "sync", "events"],
        kind = "checkbox",
        section = "sync_integrations"
    )]
    pub enable_calendar_sync: bool,
    #[setting(
        label = "Enable Bidirectional Google Tasks Sync",
        description = "Self explanatory.",
        keywords = ["google", "tasks", "sync", "todos"],
        kind = "checkbox",
        section = "sync_integrations"
    )]
    pub enable_tasks_sync: bool,
    #[setting(
        label = "Sync Interval (minutes)",
        keywords = ["sync", "interval", "poll", "time"],
        kind = "number",
        section = "sync_integrations",
        min = 1
    )]
    pub sync_interval: i32,
    #[setting(
        label = "Open Launcher",
        keywords = ["keyboard", "shortcut", "launcher", "open"],
        kind = "keybinding",
        section = "keybindings"
    )]
    pub keybinding_launcher: String,
    #[setting(
        label = "Open Settings",
        keywords = ["keyboard", "shortcut", "settings", "open"],
        kind = "keybinding",
        section = "keybindings"
    )]
    pub keybinding_open_settings: String,
    #[setting(
        label = "Restore App",
        keywords = ["keyboard", "shortcut", "restore", "maximize", "mini tracker", "minitracker"],
        kind = "keybinding",
        section = "keybindings"
    )]
    pub keybinding_restore_app: String,
    #[setting(
        label = "Show Window Border",
        keywords = ["tracker", "border", "show", "outline"],
        kind = "checkbox",
        section = "tracker_appearance"
    )]
    pub tracker_show_border: bool,
    #[setting(
        label = "Base Opacity (%)",
        description = "The baseline opacity of the mini tracker window (0 to 100).",
        keywords = ["tracker", "opacity", "transparent", "window"],
        kind = "number",
        section = "tracker_appearance",
        min = 0,
        max = 100
    )]
    pub tracker_opacity: i32,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            default_calendar_view: "month".to_string(),
            day_timeline_start_view: 300,
            default_task_duration: 0,
            clock_style: "guzey".to_string(),
            allow_stopwatch_without_task: false,
            flowtime_break_divisor: 5,
            enable_calendar_sync: true,
            enable_tasks_sync: true,
            sync_interval: 5,
            keybinding_launcher: "Meta+Shift+Space".to_string(),
            keybinding_open_settings: "Ctrl+,".to_string(),
            keybinding_restore_app: "Ctrl+Alt+R".to_string(),
            tracker_show_border: true,
            tracker_opacity: 80,
        }
    }
}

/// The settings screen's tab/section/setting metadata, derived from the
/// `#[setting(..)]` attributes on [`AppSettings`].
#[tauri::command]
#[must_use]
pub fn get_settings_schema() -> Value {
    metadata::settings_schema_value()
}

#[tauri::command]
pub async fn get_settings(app: tauri::AppHandle) -> Result<AppSettings, AppError> {
    let pool = crate::db_pool(&app)?;
    storage::read_settings(&pool).await
}

#[tauri::command]
pub async fn update_setting(
    app: tauri::AppHandle,
    key: String,
    value: Value,
) -> Result<(), AppError> {
    let pool = crate::db_pool(&app)?;
    storage::write_setting(&pool, &key, &value).await
}

/// Read per-component UI state (filters, sorts, view modes, pane sizes) from the
/// dedicated `ui_state` table. Returns `null` for an unknown key.
#[tauri::command]
pub async fn get_ui_state(app: tauri::AppHandle, key: String) -> Result<Value, AppError> {
    let pool = crate::db_pool(&app)?;
    storage::read_ui_state(&pool, &key).await
}

/// Persist per-component UI state. See [`get_ui_state`].
#[tauri::command]
pub async fn set_ui_state(
    app: tauri::AppHandle,
    key: String,
    value: Value,
) -> Result<(), AppError> {
    let pool = crate::db_pool(&app)?;
    storage::write_ui_state(&pool, &key, &value).await
}
