// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { default_calendar_view: string, day_timeline_start_view: number, default_task_duration: number, clock_style: string, allow_stopwatch_without_task: boolean, flowtime_break_divisor: number, enable_calendar_sync: boolean, enable_tasks_sync: boolean, sync_interval: number, keybinding_launcher: string, keybinding_open_settings: string, keybinding_restore_app: string, tracker_show_border: boolean, tracker_opacity: number, };
