export type SettingValue = string | number | boolean;

export type SettingType = 'select' | 'checkbox' | 'number' | 'time' | 'keybinding' | 'custom' | 'action';

export interface SettingOption {
    value: SettingValue;
    label: string;
}

export interface SettingsSchemaItem {
    id: string;
    label: string;
    description?: string;
    keywords?: string[];
    type: SettingType;
    options?: SettingOption[];
    min?: number;
    max?: number;
    defaultValue?: SettingValue;
    danger?: boolean;
}

export interface SettingSection {
    name: string;
    settings: SettingsSchemaItem[];
}

export interface SettingTab {
    id: string;
    label: string;
    sections: SettingSection[];
}

export interface SettingsSchema {
    tabs: SettingTab[];
}

import type { AppSettings as GeneratedAppSettings } from '../../lib/bindings/AppSettings.generated';

/**
 * The schema types below describe the JSON returned by the `get_settings_schema`
 * command; `AppSettings` is generated by ts-rs from the Rust struct.
 * Intersected with a string-key record so schema rows can index it by setting id.
 */
export type AppSettings = GeneratedAppSettings & Record<string, SettingValue>;
