//! App settings and per-component UI state storage.
//!
//! Two channels back persisted state:
//! - Typed, user-facing app settings are `AppSettings` fields stored as JSON rows
//!   in the `settings` table and read/written with [`get_settings`] / [`update_setting`].
//! - Arbitrary per-component UI state (filters, sorts, view modes, pane sizes)
//!   lives in the dedicated `ui_state` table via [`get_ui_state`] / [`set_ui_state`].
//!
//! The rule: if it is a typed app setting, it belongs in `AppSettings`; anything
//! else the frontend wants to remember goes to `ui_state`. Never smuggle UI state
//! into `settings` as ad-hoc `ui.*` keys. (The `settings` table also carries the
//! `google_*` OAuth rows written by `auth.rs`; those are not settings and are not
//! part of `AppSettings`.)
//!
//! Settings presentation metadata lives in `#[setting(..)]` attributes next to the
//! field it describes; [`get_settings_schema`] assembles the UI schema from them
//! and [`AppSettings::setting_metadata`] is generated by `#[derive(SettingsMeta)]`.
#![allow(clippy::struct_excessive_bools)]

use crate::db;
use crate::error::AppError;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use sqlx::SqlitePool;
use std::collections::HashMap;
use taskroot_macros::SettingsMeta;
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, Deserialize, TS, SettingsMeta)]
#[ts(export, export_to = "../../src/lib/bindings/AppSettings.generated.ts")]
#[serde(default)]
pub struct AppSettings {
    #[setting(
        label = "Default View",
        keywords = ["calendar", "view", "month", "week"],
        kind = "select",
        section = "plan_calendar",
        options = [("month", "Month"), ("week", "Week")]
    )]
    pub default_calendar_view: String,
    #[setting(
        label = "Timeline View Start Time",
        keywords = ["timeline", "day", "start", "time", "scroll", "view"],
        kind = "time",
        section = "plan_calendar"
    )]
    pub day_timeline_start_view: i32,
    #[setting(
        label = "Default Duration",
        keywords = ["task", "duration", "estimate", "time"],
        kind = "select",
        section = "plan_calendar",
        options = [(0, "Not set"), (15, "15m"), (30, "30m"), (45, "45m")]
    )]
    pub default_task_duration: i32,
    #[setting(
        label = "Clock Style",
        keywords = ["stopwatch", "timer", "guzey", "counter", "flowtime"],
        kind = "select",
        section = "do_stopwatch",
        options = [
            ("counter", "Counter"),
            ("flowtime", "Flowtime"),
            ("guzey", "Guzey")
        ]
    )]
    pub clock_style: String,
    #[setting(
        label = "Allow stopwatch use without selecting task",
        keywords = ["stopwatch", "task", "requirement", "allow"],
        kind = "checkbox",
        section = "do_stopwatch"
    )]
    pub allow_stopwatch_without_task: bool,
    #[setting(
        label = "Flowtime Break Divisor",
        description = "How much break time you earn (e.g. 5 means 1 min break for every 5 mins of work).",
        keywords = ["flowtime", "break", "divisor", "rest"],
        kind = "number",
        section = "do_stopwatch",
        min = 1
    )]
    pub flowtime_break_divisor: i32,
    #[setting(
        label = "Enable Bidirectional Google Calendar Sync",
        description = "Self explanatory.",
        keywords = ["google", "calendar", "sync", "events"],
        kind = "checkbox",
        section = "sync_integrations"
    )]
    pub enable_calendar_sync: bool,
    #[setting(
        label = "Enable Bidirectional Google Tasks Sync",
        description = "Self explanatory.",
        keywords = ["google", "tasks", "sync", "todos"],
        kind = "checkbox",
        section = "sync_integrations"
    )]
    pub enable_tasks_sync: bool,
    #[setting(
        label = "Sync Interval (minutes)",
        keywords = ["sync", "interval", "poll", "time"],
        kind = "number",
        section = "sync_integrations",
        min = 1
    )]
    pub sync_interval: i32,
    #[setting(
        label = "Open Launcher",
        keywords = ["keyboard", "shortcut", "launcher", "open"],
        kind = "keybinding",
        section = "keybindings"
    )]
    pub keybinding_launcher: String,
    #[setting(
        label = "Open Settings",
        keywords = ["keyboard", "shortcut", "settings", "open"],
        kind = "keybinding",
        section = "keybindings"
    )]
    pub keybinding_open_settings: String,
    #[setting(
        label = "Restore App",
        keywords = ["keyboard", "shortcut", "restore", "maximize", "mini tracker", "minitracker"],
        kind = "keybinding",
        section = "keybindings"
    )]
    pub keybinding_restore_app: String,
    #[setting(
        label = "Show Window Border",
        keywords = ["tracker", "border", "show", "outline"],
        kind = "checkbox",
        section = "tracker_appearance"
    )]
    pub tracker_show_border: bool,
    #[setting(
        label = "Base Opacity (%)",
        description = "The baseline opacity of the mini tracker window (0 to 100).",
        keywords = ["tracker", "opacity", "transparent", "window"],
        kind = "number",
        section = "tracker_appearance",
        min = 0,
        max = 100
    )]
    pub tracker_opacity: i32,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            default_calendar_view: "month".to_string(),
            day_timeline_start_view: 300,
            default_task_duration: 0,
            clock_style: "guzey".to_string(),
            allow_stopwatch_without_task: false,
            flowtime_break_divisor: 5,
            enable_calendar_sync: true,
            enable_tasks_sync: true,
            sync_interval: 5,
            keybinding_launcher: "Meta+Shift+Space".to_string(),
            keybinding_open_settings: "Ctrl+,".to_string(),
            keybinding_restore_app: "Ctrl+Alt+R".to_string(),
            tracker_show_border: true,
            tracker_opacity: 80,
        }
    }
}

/// One setting's presentation metadata, generated by `#[derive(SettingsMeta)]`.
///
/// Serialized into the `get_settings_schema` payload. `section` is not serialized:
/// it only routes the setting into the right tab/section during assembly.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SettingMeta {
    pub id: String,
    pub label: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub keywords: Vec<String>,
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<SettingOption>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_value: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub danger: Option<bool>,
    #[serde(skip)]
    pub section: &'static str,
}

/// A select option; `value` is JSON so it can be a string or a number.
#[derive(Debug, Clone, Serialize)]
pub struct SettingOption {
    pub value: Value,
    pub label: String,
}

/// A tab/section in the settings screen. `key` is what `#[setting(section = ..)]`
/// references; tabs are grouped in first-appearance order.
struct SectionDef {
    key: &'static str,
    tab: &'static str,
    tab_label: &'static str,
    name: &'static str,
}

const SETTING_SECTIONS: &[SectionDef] = &[
    SectionDef {
        key: "plan_calendar",
        tab: "plan_screen",
        tab_label: "Plan screen",
        name: "Calendar",
    },
    SectionDef {
        key: "do_stopwatch",
        tab: "do_screen",
        tab_label: "Do screen",
        name: "Stopwatch",
    },
    SectionDef {
        key: "sync_integrations",
        tab: "sync",
        tab_label: "Sync and Backup",
        name: "Sync & Integrations",
    },
    SectionDef {
        key: "sync_danger",
        tab: "sync",
        tab_label: "Sync and Backup",
        name: "Danger Zone",
    },
    SectionDef {
        key: "keybindings",
        tab: "keybindings",
        tab_label: "Keybindings",
        name: "Keybindings",
    },
    SectionDef {
        key: "tracker_appearance",
        tab: "tracker_window",
        tab_label: "Tracker window",
        name: "Appearance",
    },
];

/// Button-only settings that act on the app rather than storing a value.
struct CustomSettingDef {
    section: &'static str,
    id: &'static str,
    label: &'static str,
    description: &'static str,
    keywords: &'static [&'static str],
    danger: bool,
}

const CUSTOM_SETTINGS: &[CustomSettingDef] = &[
    CustomSettingDef {
        section: "sync_integrations",
        id: "logout",
        label: "Sign out",
        description: "Sign out of your Google account.",
        keywords: &["logout", "signout", "google", "account"],
        danger: false,
    },
    CustomSettingDef {
        section: "sync_danger",
        id: "clear_all_data",
        label: "Clear All Data",
        description: "Permanently delete all your tasks, settings, logs, and other data from both this device and the cloud. This cannot be undone.",
        keywords: &["delete", "clear", "wipe", "reset", "factory", "all"],
        danger: true,
    },
];

#[derive(Serialize)]
struct SchemaSection {
    name: &'static str,
    settings: Vec<SettingMeta>,
}

#[derive(Serialize)]
struct SchemaTab {
    id: &'static str,
    label: &'static str,
    sections: Vec<SchemaSection>,
}

#[derive(Serialize)]
struct SchemaRoot {
    tabs: Vec<SchemaTab>,
}

fn custom_setting_meta(def: &CustomSettingDef) -> SettingMeta {
    SettingMeta {
        id: def.id.to_string(),
        label: def.label.to_string(),
        description: Some(def.description.to_string()),
        keywords: def.keywords.iter().map(|word| (*word).to_string()).collect(),
        kind: "custom".to_string(),
        options: None,
        min: None,
        max: None,
        default_value: None,
        danger: def.danger.then_some(true),
        section: def.section,
    }
}

fn build_settings_schema() -> SchemaRoot {
    let mut tabs: Vec<SchemaTab> = Vec::new();
    let metadata = AppSettings::setting_metadata();

    for def in SETTING_SECTIONS {
        let mut settings: Vec<SettingMeta> = metadata
            .iter()
            .filter(|meta| meta.section == def.key)
            .cloned()
            .collect();
        settings.extend(
            CUSTOM_SETTINGS
                .iter()
                .filter(|custom| custom.section == def.key)
                .map(custom_setting_meta),
        );

        let section = SchemaSection {
            name: def.name,
            settings,
        };

        if let Some(tab) = tabs.iter_mut().find(|tab| tab.id == def.tab) {
            tab.sections.push(section);
        } else {
            tabs.push(SchemaTab {
                id: def.tab,
                label: def.tab_label,
                sections: vec![section],
            });
        }
    }

    SchemaRoot { tabs }
}

/// The settings screen's tab/section/setting metadata, derived from the
/// `#[setting(..)]` attributes on [`AppSettings`].
#[tauri::command]
#[must_use]
pub fn get_settings_schema() -> Value {
    // `SchemaRoot` is plain data, so serialization is infallible.
    serde_json::to_value(build_settings_schema()).unwrap_or(Value::Null)
}

fn defaults_object() -> Result<Map<String, Value>, AppError> {
    match serde_json::to_value(AppSettings::default()) {
        Ok(Value::Object(map)) => Ok(map),
        Ok(_) => Err(AppError::Internal(
            "Settings defaults are not a JSON object".to_string(),
        )),
        Err(e) => Err(AppError::Internal(format!(
            "Failed to serialize settings defaults: {e}"
        ))),
    }
}

/// Decode one stored `settings.value` / `ui_state.value` column into JSON.
///
/// Values are JSON by construction; a bare string (an older row or a hand-edited
/// database) falls back to `Value::String` so one malformed row cannot break a
/// whole read path.
#[must_use]
pub fn decode_stored_value(raw: &str) -> Value {
    serde_json::from_str(raw).unwrap_or_else(|_| Value::String(raw.to_string()))
}

/// Decode an optional stored column. Missing keys become `Null` so the frontend
/// can distinguish "never saved" from a stored `null`.
#[must_use]
pub fn parse_setting_value(raw: Option<&str>) -> Value {
    raw.map_or(Value::Null, decode_stored_value)
}

async fn load_stored_settings(pool: &SqlitePool) -> Result<HashMap<String, Value>, AppError> {
    let rows: Vec<(String, String)> = sqlx::query_as("SELECT key, value FROM settings")
        .fetch_all(pool)
        .await?;

    Ok(rows
        .into_iter()
        .map(|(key, value)| (key, decode_stored_value(&value)))
        .collect())
}

/// Whether `value` round-trips through the serde type of the `AppSettings` field
/// `key`.
///
/// The probe is a one-field object; the struct's container-level `#[serde(default)]`
/// fills every other field from `AppSettings::default()`, so only `key` is
/// exercised. The struct itself therefore defines which values are acceptable and
/// no hand-maintained list of JSON variants can drift out of sync.
fn accepts_field_value(key: &str, value: &Value) -> bool {
    let mut probe = Map::new();
    probe.insert(key.to_string(), value.clone());
    serde_json::from_value::<AppSettings>(Value::Object(probe)).is_ok()
}

/// Reject a known `AppSettings` key whose value cannot be deserialized into its
/// field, instead of storing a value [`get_settings`] will silently ignore.
///
/// Unknown keys stay allowed so the command remains a generic key/value setter.
fn ensure_valid_setting_value(key: &str, value: &Value) -> Result<(), AppError> {
    let defaults = defaults_object()?;
    if defaults.contains_key(key) && !accepts_field_value(key, value) {
        return Err(AppError::InvalidInput(format!(
            "Setting '{key}' does not accept the provided value"
        )));
    }
    Ok(())
}

/// Merge stored rows over the defaults: unknown keys are ignored, and a known key
/// whose stored value cannot be deserialized into its field keeps the default.
fn apply_stored_settings(stored: HashMap<String, Value>) -> Result<AppSettings, AppError> {
    let mut merged = defaults_object()?;

    for (key, value) in stored {
        if merged.contains_key(&key) && accepts_field_value(&key, &value) {
            merged.insert(key, value);
        }
    }

    serde_json::from_value(Value::Object(merged))
        .map_err(|e| AppError::Internal(format!("Stored settings failed validation: {e}")))
}

#[tauri::command]
pub async fn get_settings(app: tauri::AppHandle) -> Result<AppSettings, AppError> {
    let pool = crate::db_pool(&app)?;
    let stored = load_stored_settings(&pool).await?;
    apply_stored_settings(stored)
}

#[tauri::command]
pub async fn update_setting(
    app: tauri::AppHandle,
    key: String,
    value: Value,
) -> Result<(), AppError> {
    ensure_valid_setting_value(&key, &value)?;
    let pool = crate::db_pool(&app)?;

    let value_str = serde_json::to_string(&value)
        .map_err(|e| AppError::Internal(format!("Failed to serialize setting: {e}")))?;

    db::set_setting(&pool, &key, &value_str).await?;
    Ok(())
}

/// Read per-component UI state (filters, sorts, view modes, pane sizes) from the
/// dedicated `ui_state` table. Returns `null` for an unknown key.
#[tauri::command]
pub async fn get_ui_state(app: tauri::AppHandle, key: String) -> Result<Value, AppError> {
    let pool = crate::db_pool(&app)?;
    let raw = db::get_ui_state(&pool, &key).await?;
    Ok(parse_setting_value(raw.as_deref()))
}

/// Persist per-component UI state. See [`get_ui_state`].
#[tauri::command]
pub async fn set_ui_state(
    app: tauri::AppHandle,
    key: String,
    value: Value,
) -> Result<(), AppError> {
    let pool = crate::db_pool(&app)?;

    let value_str = serde_json::to_string(&value)
        .map_err(|e| AppError::Internal(format!("Failed to serialize UI state: {e}")))?;

    db::set_ui_state(&pool, &key, &value_str).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;
    use std::collections::BTreeSet;

    fn stored(entries: &[(&str, Value)]) -> HashMap<String, Value> {
        entries
            .iter()
            .map(|(key, value)| ((*key).to_string(), value.clone()))
            .collect()
    }

    fn schema_setting_ids() -> Vec<String> {
        let schema = serde_json::to_value(build_settings_schema()).expect("schema serializes");
        let mut ids = Vec::new();

        for tab in schema["tabs"].as_array().expect("tabs") {
            for section in tab["sections"].as_array().expect("sections") {
                for setting in section["settings"].as_array().expect("settings") {
                    ids.push(setting["id"].as_str().expect("id").to_string());
                }
            }
        }

        ids
    }

    #[test]
    fn parse_setting_value_returns_null_for_missing_key() {
        assert_eq!(parse_setting_value(None), Value::Null);
    }

    #[test]
    fn parse_setting_value_decodes_stored_json() {
        let raw = Some(r#"[{"column":"status","value":["done"]}]"#);

        let parsed = parse_setting_value(raw);

        let first = parsed.as_array().expect("array").first().expect("item");
        assert_eq!(first["column"], Value::String("status".to_string()));
    }

    #[test]
    fn parse_setting_value_falls_back_to_raw_string() {
        assert_eq!(
            parse_setting_value(Some("not json")),
            Value::String("not json".to_string())
        );
    }

    #[test]
    fn apply_stored_settings_keeps_defaults_for_missing_keys() {
        let settings = apply_stored_settings(HashMap::new()).expect("valid settings");

        assert_eq!(settings.clock_style, AppSettings::default().clock_style);
    }

    #[test]
    fn apply_stored_settings_overrides_a_correctly_typed_value() {
        let settings = apply_stored_settings(stored(&[(
            "clock_style",
            Value::String("counter".to_string()),
        )]))
        .expect("valid settings");

        assert_eq!(settings.clock_style, "counter");
    }

    #[test]
    fn apply_stored_settings_ignores_a_wrongly_typed_value() {
        let settings = apply_stored_settings(stored(&[("clock_style", serde_json::json!(42))]))
            .expect("valid settings");

        assert_eq!(settings.clock_style, AppSettings::default().clock_style);
    }

    #[test]
    fn apply_stored_settings_ignores_structured_values_and_unknown_keys() {
        let settings = apply_stored_settings(stored(&[
            ("clock_style", serde_json::json!(["guzey"])),
            ("sync_interval", Value::Null),
            ("google_access_token", Value::String("token".to_string())),
        ]))
        .expect("structured values and unknown keys must be ignored");

        assert_eq!(
            serde_json::to_value(&settings).expect("settings serialize"),
            serde_json::to_value(AppSettings::default()).expect("defaults serialize")
        );
    }

    #[test]
    fn apply_stored_settings_ignores_a_non_integer_number_without_failing_the_read() {
        let settings = apply_stored_settings(stored(&[
            ("sync_interval", serde_json::json!(1.5)),
            ("clock_style", Value::String("counter".to_string())),
        ]))
        .expect("one bad field must not fail the read");

        assert_eq!(settings.sync_interval, AppSettings::default().sync_interval);
        assert_eq!(settings.clock_style, "counter");
    }

    #[test]
    fn apply_stored_settings_keeps_booleans_and_numbers() {
        let settings = apply_stored_settings(stored(&[
            ("enable_calendar_sync", Value::Bool(false)),
            ("sync_interval", serde_json::json!(15)),
        ]))
        .expect("valid settings");

        assert!(!settings.enable_calendar_sync);
        assert_eq!(settings.sync_interval, 15);
    }

    #[test]
    fn setting_metadata_covers_every_appsettings_field_exactly_once() {
        let metadata = AppSettings::setting_metadata();
        let ids: Vec<String> = metadata.iter().map(|meta| meta.id.clone()).collect();
        let unique: BTreeSet<String> = ids.iter().cloned().collect();
        assert_eq!(unique.len(), ids.len(), "duplicate metadata id");

        let defaults = serde_json::to_value(AppSettings::default()).expect("defaults");
        let expected: BTreeSet<String> = defaults
            .as_object()
            .expect("defaults object")
            .keys()
            .cloned()
            .collect();

        assert_eq!(unique, expected);
    }

    #[test]
    fn setting_metadata_default_values_match_appsettings_defaults() {
        let defaults = serde_json::to_value(AppSettings::default()).expect("defaults");

        for meta in AppSettings::setting_metadata() {
            assert_eq!(
                meta.default_value.as_ref(),
                defaults.get(&meta.id),
                "{}",
                meta.id
            );
        }
    }

    #[test]
    fn schema_places_every_setting_exactly_once() {
        let ids = schema_setting_ids();
        let unique: BTreeSet<String> = ids.iter().cloned().collect();
        assert_eq!(unique.len(), ids.len(), "duplicate setting id in schema");

        let mut expected: BTreeSet<String> = AppSettings::setting_metadata()
            .iter()
            .map(|meta| meta.id.clone())
            .collect();
        expected.insert("logout".to_string());
        expected.insert("clear_all_data".to_string());

        assert_eq!(unique, expected);
    }

    #[test]
    fn numeric_select_options_keep_numeric_values() {
        let metadata = AppSettings::setting_metadata();
        let duration = metadata
            .iter()
            .find(|meta| meta.id == "default_task_duration")
            .expect("default_task_duration metadata");
        let options = duration.options.as_ref().expect("options");

        assert_eq!(
            options.first().map(|option| &option.value),
            Some(&serde_json::json!(0))
        );
        assert_eq!(
            options.get(1).map(|option| &option.value),
            Some(&serde_json::json!(15))
        );
    }

    #[test]
    fn ensure_valid_setting_value_rejects_a_wrongly_typed_known_setting() {
        let error = ensure_valid_setting_value("sync_interval", &serde_json::json!("15"))
            .expect_err("a string must be rejected for an i32 setting");

        assert_eq!(error.code(), "invalid-input");
    }

    #[test]
    fn ensure_valid_setting_value_accepts_typed_values_and_unknown_keys() {
        ensure_valid_setting_value("sync_interval", &serde_json::json!(15))
            .expect("a number is valid");
        ensure_valid_setting_value("not_a_setting", &serde_json::json!([1, 2]))
            .expect("unknown keys stay generic");
    }
}
